package pe.edu.unsch.entities;
// Generated 05-jul-2019 15:27:14 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "cargabd")
public class Docente implements java.io.Serializable {

	private int iddocente;
	private String nombre;
	private String apelido;
	private String doc;
	private Set<Carga> cargas = new HashSet<Carga>(0);

	public Docente() {
	}

	public Docente(int iddocente, String nombre, String apelido, String doc) {
		this.iddocente = iddocente;
		this.nombre = nombre;
		this.apelido = apelido;
		this.doc = doc;
	}

	public Docente(int iddocente, String nombre, String apelido, String doc, Set<Carga> cargas) {
		this.iddocente = iddocente;
		this.nombre = nombre;
		this.apelido = apelido;
		this.doc = doc;
		this.cargas = cargas;
	}

	@Id

	@Column(name = "iddocente", unique = true, nullable = false)
	public int getIddocente() {
		return this.iddocente;
	}

	public void setIddocente(int iddocente) {
		this.iddocente = iddocente;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apelido", nullable = false, length = 50)
	public String getApelido() {
		return this.apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}

	@Column(name = "doc", nullable = false, length = 8)
	public String getDoc() {
		return this.doc;
	}

	public void setDoc(String doc) {
		this.doc = doc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<Carga> getCargas() {
		return this.cargas;
	}

	public void setCargas(Set<Carga> cargas) {
		this.cargas = cargas;
	}

}
