package pe.edu.unsch.entities;
// Generated 05-jul-2019 15:27:14 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "semestre", catalog = "cargabd")
public class Semestre implements java.io.Serializable {

	private int idsemestre;
	private String nombre;
	private Date anio;

	public Semestre() {
	}

	public Semestre(int idsemestre, String nombre, Date anio) {
		this.idsemestre = idsemestre;
		this.nombre = nombre;
		this.anio = anio;
	}

	@Id

	@Column(name = "idsemestre", unique = true, nullable = false)
	public int getIdsemestre() {
		return this.idsemestre;
	}

	public void setIdsemestre(int idsemestre) {
		this.idsemestre = idsemestre;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anio", nullable = false, length = 10)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

}
